# Ca ca veut dire que cette partie de la pipeline (le "job") ca se faire sur une machine linux avec la dernière version de python installée
image: python:latest

# ca ca veut dire que je veux utiliser gitlab Pages (le service qui permet de mettre un site statique en ligne)
create-pages:

# ca c'est la config de gitlab pages (en gros c'est l'url de "où se trouvent les fichiers qu'il doit servir dans le repo"
  pages:
    publish: docs/site

# ca c'est pour dire QUAND la pipeline/le job doit se lancer. En gros ca veut dire "quand il y a un nouveau commit sur la branche main"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

# ca c'est les cmd qu'il doit faire dans un terminal au début du job (installation de truc etc.)
  before_script:
    - pip install mkdocs
    - cd ma_super_doc

# ca c'est les cmd qu'il doit faire pour "faire le job" (en l'occurance build le site)
  script:
    - mkdocs build

# voilafffff


